name: istoreto
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # GetX state management
  get: ^4.6.6
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.10.1
  google_fonts: ^6.3.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.2.0
  sizer: ^3.1.3
  shimmer: ^3.0.0
  image_cropper:
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5
  readmore: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  dotted_border: ^2.1.0
  flutter_phone_number_field: ^1.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^4.0.1
  flutter_speed_dial: ^7.0.0
  carousel_slider: ^5.1.1
  image: ^4.5.4
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  file_picker: ^8.1.5
  get_storage: ^2.1.1
  pull_down_button: ^0.10.2
  share_plus: ^12.0.0
  permission_handler: ^12.0.1
  photo_manager: ^3.7.1
  photo_view: ^0.15.0
  flutter_image_compress: ^2.4.0
  simple_loading_dialog: ^1.0.0
  connectivity_plus: ^7.0.0
  loading_animation_widget: ^1.3.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.1
  path_provider: ^2.1.5
  app_links: ^6.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
